language: node_js
node_js:
  - 'stable'
  - '12'
  - '10'

cache:
  directories:
    - node_modules

# Lint errors should trigger a failure.
before_script: npm run lint && npm run build

# Code coverage
script: npm run coveralls
